<?php
defined( 'ABSPATH' ) || exit;

function brounhall_seed_doctor( $doctor ) {
	$post = get_page_by_path( $doctor['slug'], OBJECT, 'bh_doctor' );
	$id = $post ? $post->ID : wp_insert_post( array( 'post_type' => 'bh_doctor', 'post_status' => 'publish', 'post_title' => $doctor['name'], 'post_name' => $doctor['slug'], 'menu_order' => $doctor['order'] ) );
	if ( is_wp_error( $id ) || ! $id ) { return 0; }
	if ( ! $post ) { update_post_meta( $id, '_brounhall_doctor_data', wp_json_encode( brounhall_normalize_doctor_data( $doctor ), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ); }
	return (int) $id;
}

function brounhall_seed_embryologists() {
	$members = array(
		array( 'order' => 1, 'slug' => 'geraldine-emerson', 'name' => 'Geraldine Emerson', 'type' => 'embryologist', 'role' => 'Group Laboratory Director', 'clinic' => 'Dubai' ),
		array( 'order' => 2, 'slug' => 'linda-bouhafs', 'name' => 'Linda Bouhafs', 'type' => 'embryologist', 'role' => 'Laboratory Operations Director', 'clinic' => 'Abu Dhabi' ),
		array( 'order' => 3, 'slug' => 'eman-ahmad', 'name' => 'Eman Ahmad', 'type' => 'embryologist', 'role' => 'Laboratory Manager', 'clinic' => 'Dubai' ),
		array( 'order' => 4, 'slug' => 'dalya-hassan', 'name' => 'Dalya Hassan', 'type' => 'embryologist', 'role' => 'Laboratory Manager', 'clinic' => 'Abu Dhabi' ),
		array( 'order' => 5, 'slug' => 'ruba-najjar', 'name' => 'Ruba Najjar', 'type' => 'embryologist', 'role' => 'Senior Clinical Embryologist', 'clinic' => 'Dubai' ),
		array( 'order' => 6, 'slug' => 'madiha-mustafa', 'name' => 'Madiha Mustafa', 'type' => 'embryologist', 'role' => 'Senior Clinical Embryologist', 'clinic' => 'Dubai' ),
		array( 'order' => 7, 'slug' => 'sanaa-maalouf', 'name' => 'Sanaa Maalouf', 'type' => 'embryologist', 'role' => 'Senior Clinical Embryologist', 'clinic' => 'Abu Dhabi' ),
		array( 'order' => 8, 'slug' => 'ahmed-mohammed-nasr', 'name' => 'Ahmed Mohammed Nasr', 'type' => 'embryologist', 'role' => 'Senior Clinical Embryologist', 'clinic' => 'Al Ain' ),
		array( 'order' => 9, 'slug' => 'sami-elhadi', 'name' => 'Sami Elhadi', 'type' => 'embryologist', 'role' => 'Medical Laboratory Technologist', 'clinic' => 'Dubai' ),
	);
	foreach ( $members as $member ) { brounhall_seed_doctor( $member ); }
}

function brounhall_seed_doctors() {
	$doctors = array(
		array( 'order' => 1, 'slug' => 'dr-ghada-hussein', 'name' => 'Dr. Ghada Hussein', 'role' => 'Medical Director', 'headline' => 'Medical Director, Consultant in Reproductive Medicine and Infertility', 'specialty' => 'Consultant, Reproductive Medicine', 'clinic' => 'Abu Dhabi', 'imageAlt' => 'Dr. Ghada Hussein', 'nationality' => 'Swedish, Iraqi', 'languages' => 'Arabic, English, Swedish fluently', 'areasOfInterest' => 'Infertility challenges including poor ovarian reserve, severe male factor infertility, severe PCOS with amenorrhoea and repeated failures, as well as endometriosis and helping families with history of genetic disorders. Uterine factor infertility including fibroids with a novel and new surgical procedure that was first introduced in UAE by Dr. Ghada Hussein using radio frequency ablation. Psychological wellbeing of couples undergoing infertility treatment.', 'education' => 'Fellowship gained from Gothenburg University, Sweden (PhD) in Reproductive Physiology. Swedish board of Obstetrics and Gynaecology. GMC licensed physician in UK.', 'bio' => 'Dr. Ghada Hussein is the medical director of Bourn Hall IVF clinic in Abu Dhabi. She is a senior consultant OBGYN with more than 25 years of experience in reproductive endocrinology and infertility covering both the clinical and laboratory part of the field. She has worked in many countries including Iraq, Jordan, Qatar and Sweden and was the medical director of an IVF clinic in Stockholm.' ),
		array( 'order' => 2, 'slug' => 'dr-sajida-detho', 'name' => 'Dr. Sajida Detho', 'role' => 'Medical Director', 'headline' => 'Medical Director and Consultant in Reproductive Medicine and Infertility', 'specialty' => 'Consultant, Reproductive Medicine', 'clinic' => 'Al Ain', 'imageAlt' => 'Dr. Sajida Detho', 'nationality' => 'Irish', 'languages' => 'English, Urdu, Hindi, Sindhi, Punjabi', 'areasOfInterest' => 'Recurrent IVF failure, repeated miscarriages, chromosomal disorders, thin endometrium and poor egg reserve, male factor infertility, hysteroscopy and laparoscopy, PRP, and egg preservation for oncology patients.', 'education' => 'MBBS, FRCOG, DOWH, MRCPI (Ireland), Diploma in minimal access surgery (Germany).', 'bio' => 'Dr. Sajida is a Medical Director and Consultant in Reproductive Medicine and Infertility of Bourn Hall Al Ain and has 25 years of experience in Obstetrics and Gynaecology, Infertility and IVF. Dr Sajida graduated MBBS in 1996 from Pakistan and moved to Europe to gain experience in some of the world’s leading IVF units, such as Rotunda Hospital where she spent over 12 years. She pioneered successful natural IVF baby in Ireland. Dr Sajida established Fakih IVF Al Ain and was Medical Director there for 8 years. Dr Sajida is a strong believer in a holistic approach to infertility and IVF. She is a fellow of the Royal College of Obstetrics and Gynaecology Ireland and UK, a member of ESHRE and ASRM, and a trainer in Assisted Reproduction and IVF from the British Fertility Society UK.' ),
		array( 'order' => 3, 'slug' => 'dr-shazia-magray', 'name' => 'Dr. Shazia Magray', 'role' => 'Specialist Reproductive Medicine', 'headline' => 'Specialist Obstetrics and Gynecology / Specialist Reproductive Medicine and Infertility', 'specialty' => 'Specialist, Reproductive Medicine', 'clinic' => 'Dubai', 'imageAlt' => 'Dr. Shazia Magray', 'nationality' => 'Indian', 'languages' => 'English, Urdu, Hindi', 'areasOfInterest' => 'Endometriosis and infertility, recurrent pregnancy loss (RPL), early pregnancy assessment, polycystic ovarian syndrome (PCOS), and management of dysfunctional uterine bleeding.', 'education' => 'Master’s Degree in Biotechnology of Human Assisted Reproduction and Embryology at IVI Valencia, Spain. Doctor of Medicine Degree from the University of Kashmir, India (2008). Clinical Fellowship in Reproductive Medicine at the University of South Alabama, USA. ART training at Cleveland Clinic, USA and the University of Kiel, Germany. Member of the Royal College of Obstetricians and Gynaecologists, London.', 'bio' => 'Dr. Shazia joined Bourn Hall Fertility Clinic – Dubai, in 2016 after completing her Clinical Fellowship in Reproductive Medicine at the University of South Alabama, USA. Before joining Bourn Hall Fertility Clinic, Dr. Shazia received rigorous training in Assisted Reproductive Technology (ART) from the reputed Cleveland Clinic, USA and the University of Kiel, Germany and later went on to work as a Specialist in Latifa Hospital – Dubai. Dr Shazia is a Member of the Royal College of Obstetricians and Gynaecologists, London, England.' ),
		array( 'order' => 4, 'slug' => 'dr-larissa-schindler', 'name' => 'Dr. Larissa Schindler', 'role' => 'Specialist Reproductive Medicine', 'headline' => 'Specialist Reproductive Medicine and Infertility', 'specialty' => 'Specialist, Reproductive Medicine', 'clinic' => 'Dubai', 'imageAlt' => 'Dr. Larissa Schindler', 'nationality' => 'French-Brazilian', 'languages' => 'English, French, Italian, Portuguese', 'areasOfInterest' => 'Endometriosis-related infertility, gynaecological endocrinology, hysteroscopy, fertility services and general gynaecology.', 'education' => 'Postgraduate education at the University Federal of Bahia and the University Santa Casa de Misericordia of Sao Paulo in Brazil, with sub-specialisation in Infertility. Postgraduation in France at the University of Strasbourg. MD at the School of Medicine and Public Health (Brazil) in 1993 and at the University of Palermo (Italy) in 2002.', 'bio' => 'Dr Larissa Schindler is an expert in the treatment of infertile couples. She has more than 20 years of experience in the field of infertility, including nine years working at the University Hospital of Strasbourg – Louis Pasteur University in France. Additionally, she has received special training in office hysteroscopy as well as hysteroscopic intra-uterine surgery and thus manages all type of uterine pathologies such as fibroids or polyps and all endometrial pathologies. After working for several years as consultant at the University Hospital of Strasbourg, Dr Larissa moved to Dubai where she worked at the Dubai Fertility Center (DHA) for six years. She is a member of the European Society of Human Reproduction and Embryology (ESHRE), the French Medical Board and the Italian Medical Board.' ),
		array( 'order' => 5, 'slug' => 'dr-limia-ibrahim', 'name' => 'Dr. Limia Ibrahim', 'role' => 'Specialist Reproductive Medicine', 'headline' => 'Specialist in Reproductive Medicine and Infertility', 'specialty' => 'Specialist, Reproductive Medicine', 'clinic' => 'Abu Dhabi', 'imageAlt' => 'Dr. Limia Ibrahim', 'nationality' => 'British', 'languages' => 'English, Arabic, Turkish', 'areasOfInterest' => 'Challenging cases of infertility with endometriosis, fibroids, PCOS, recurrent pregnancy loss, recurrent implantation failure, genetic diseases, low reserve and male infertility.', 'education' => 'Fellow of the Royal College (FRCOG). MSc, Reproduction & Development, Bristol University, UK. Diploma in Obstetrics, RCP, Ireland. Medical Doctor, Hacettepe Medical School, Türkiye.', 'bio' => 'Dr. Limia Ibrahim has more than 23 years’ experience in her field. She is enthusiastic in dealing with fertility challenges and her goal is to preserve fertility in early ages for both women and men. By using evidence-based medical techniques, she helps families to achieve their goals of parenthood.' ),
		array( 'order' => 6, 'slug' => 'dr-majeed-aloum', 'name' => 'Dr. Majeed Aloum', 'role' => 'Consultant', 'headline' => 'Consultant in Reproductive Medicine and Infertility', 'specialty' => 'Reproductive Medicine & Infertility', 'clinic' => 'Al Ain', 'imageAlt' => 'Dr. Majeed Aloum', 'nationality' => 'British', 'languages' => 'Arabic, English', 'areasOfInterest' => 'All aspects of fertility management and assisted reproduction with special interest in recurrent implantation failure and male infertility procedures including surgical sperm retrieval.', 'education' => 'MD from Damascus University, Syria. DGO/LM diploma in Obstetrics and Gynaecology and License in Midwifery, Trinity College Dublin, Ireland. Membership of the Royal College of Obstetricians and Gynaecologists (MRCOG), London, UK (1989).', 'bio' => 'Dr Majeed Aloum has 28 years of experience in Obstetrics and Gynaecology / Reproductive Medicine and IVF with vast experience in procedures of assisted reproduction in UK, Syria and UAE. His previous positions include Director of Nottingham University Research and Treatment Unit in Reproduction (NURURE) and Lecturer and Consultant in Obstetrics and Gynaecology / Reproductive Medicine at Queen’s Medical Centre / University Hospitals, Nottingham, United Kingdom. Dr Majeed is a Member of the American Society for Reproductive Medicine (ASRM) and the European Society of Human Reproduction and Embryology (ESHRE).' ),
		array( 'order' => 7, 'slug' => 'dr-munira-furniturewala', 'name' => 'Dr. Munira Furniturewala', 'role' => 'Specialist Reproductive Medicine', 'headline' => 'Specialist Reproductive Medicine and Infertility', 'specialty' => 'Specialist, Reproductive Medicine', 'clinic' => 'Dubai', 'imageAlt' => 'Dr. Munira Furniturewala', 'nationality' => 'Indian', 'languages' => 'English, Urdu, Hindi, Gujarati', 'areasOfInterest' => 'Management of gynaecological endocrinology with a special interest in PCOS, recurrent pregnancy failure, assisted reproductive treatments, ultrasound guided operations, colposcopy, hysteroscopy and obstetrics & gynaecology ultrasounds.', 'education' => 'MD, DGO, FCPS. Bachelor’s degree in Medicine and Surgery from King Edward Memorial Hospital (KEM) Mumbai; postgraduate in Obstetrics and Gynaecology from TN Medical College, Mumbai, India. International Board-Certified Lactation Consultant. Fellow of the College of Physicians and Surgeons (Mumbai).', 'bio' => 'Dr. Munira Furniturewala is a Specialist Gynaecologist and Obstetrician with subspecialty in Reproductive Endocrinology and Infertility with over 28 years of clinical experience caring for women’s health. During the last 17 years she has specialised in Fertility Management and is experienced in providing comprehensive fertility workup and management of couples seeking conception, including advanced assisted reproductive technologies. Prior to joining Mediclinic, Dr Munira worked at Conceive Gynaecology and Fertility Center as assistant Medical Director and Fakih IVF Fertility Centre. Dr Munira is now based in Mediclinic Dubai Mall as a Specialist in Obstetrics & Gynaecology with a subspecialty in Fertility and Reproductive Medicine.' ),
		array( 'order' => 8, 'slug' => 'dr-heba-hashem', 'name' => 'Dr. Heba Hashem', 'role' => 'Specialist Obstetrics and Gynaecology', 'headline' => 'Specialist Obstetrics and Gynaecology', 'specialty' => 'Obstetrics, Gynaecology & Infertility', 'clinic' => 'Al Ain', 'imageAlt' => 'Dr. Heba Hashem', 'nationality' => 'Egyptian/American', 'languages' => 'English, Arabic, Spanish', 'areasOfInterest' => 'Antenatal care and management of high-risk pregnancy and early pregnancy disorders; management of infertility patients and patients with polycystic ovaries; ultrasound examination for obstetric and gynecologic problems; routine gynecological checkups and treating common and rare gynecologic disorders; colposcopy with biopsy for abnormal pap smear and suspicious cervical smears; different methods of contraception; menopausal disorders; and breast disorders.', 'education' => 'MBBS, MSc, MPH, MD. Master’s Degree in Sexual and Reproductive Medicine, University of South Wales, UK (2025). Master’s Degree in the Biotechnology of Human Assisted Reproduction and Embryology, Universitat de Valencia, Spain (2021). Master’s Degree in Public Health, George Washington University, USA (2022). Doctoral Degree in Obstetrics, Gynecology, and Infertility, Suez Canal University, Egypt (2015). Master’s Degree in Obstetrics & Gynaecology, Suez Canal University, Egypt (2007). Bachelor’s Degree in Medicine and Surgery, Suez Canal University, Egypt (2003). Member of ASRM, ESHRE, ISUOG and MEFS.', 'bio' => 'Dr. Heba has more than 17 years of experience in obstetrics, gynecology, and infertility treatment. She has worked in the UAE, USA, and Egypt. After completing her residency medical training, she worked as a specialist in one of the prestigious university hospitals in Egypt. She also worked at the National Institutes of Health, USA, as a clinical research fellow in reproductive medicine. She then moved to the UAE and worked in well-known private hospitals and fertility clinics in Abu Dhabi.' ),
		array( 'order' => 9, 'slug' => 'dr-ali-thwaini', 'name' => 'Dr. Ali Thwaini', 'role' => 'Consultant Urologist', 'headline' => 'Consultant Urologist', 'specialty' => 'Urology, Andrology & Male Infertility', 'clinic' => 'Dubai', 'imageAlt' => 'Dr. Ali Thwaini', 'nationality' => 'British', 'languages' => 'English, Arabic', 'areasOfInterest' => 'Uro-oncology and laparoscopy; renal, prostate and bladder cancer; stone disease (endoscopic management including laser); prostate disease with minimally invasive treatment including laser and UroLift; andrology – male sexual dysfunction (including regenerative medicine and penile prosthesis), enhancement (penile enlargement); female urinary incontinence; and infertility.', 'education' => 'Medicine at Baghdad University, Iraq. Master’s degree from Queen Mary University of London, UK. Intercollegiate Specialty Board Certificate in Urology (FRCS-Urology). Fellowship of the Royal College of Surgeons (FRCS) Ireland (1999). Jordanian Board of Urology (2000). Arab Board in Urology (2001).', 'bio' => 'Dr Ali Thwaini is a Consultant Urologist with a special interest in urological cancers, namely renal cancers. Dr Ali was the lead for renal cancers at the Belfast Health and Social Care Trust (Belfast City Hospital, Northern Ireland). His main skills are in advanced laparoscopy and renal cancer and renal reconstruction procedures. Dr. Ali is also an Honorary Clinical Lecturer at Queens University, Belfast, with over 40 Medline publications in the field. After completing his degree, Dr. Ali relocated to Jordan where he started his career in Urology at the Royal Medical Services, then moved to Abu Dhabi where he worked for three years as a specialist at SKMC. In 2004 he moved to the UK, finished his MD from Queen Mary University of London, and entered the UK national higher training scheme in Urology in Northern Ireland. He completed training in 2012 with FRCS-Urology and CCT UK-wide accreditation.' ),
		array( 'order' => 10, 'slug' => 'dr-gautam-allahbadia', 'name' => 'Dr. Gautam Allahbadia', 'role' => 'Consultant', 'headline' => 'Consultant Reproductive Medicine and Infertility', 'specialty' => 'Assisted Reproduction & IVF', 'clinic' => 'Dubai', 'imageAlt' => 'Dr. Gautam Allahbadia', 'nationality' => 'Indian', 'languages' => 'English, Urdu', 'areasOfInterest' => 'Assisted Reproduction Techniques (ART), IVF, IVF Lite, PGT-A, PGT-M, and ultrasound-guided embryo transfers.', 'education' => 'MD – Obstetrics & Gynaecology from Lokmanya Tilak Municipal Medical College and General Hospital (1990). Diplomat of National Board (DNB) in Obstetrics and Gynaecology, FNAMS, FCPS – Mid. & Gynae, DGO, D.F.P, FICMU, FICOG, MBBS.', 'bio' => 'Dr Gautam Allahbadia is a Medical Professional with over 25 years expertise of Assisted Reproductive Techniques. Dr. Gautam is a noted world-authority on Ultrasound Guided Embryo Transfers and one of the pioneers in Minimal Stimulation IVF (IVF Lite) in South-East Asia. He has authored over 150 scientific papers, 134 book chapters and 27 textbooks, the latest of which is a comprehensive text, entitled “Minimal Stimulation IVF”. He is currently the Editor Emeritus of the Journal of Obstetrics & Gynaecology of India & the IVF Lite (Journal of Minimal Stimulation IVF). Throughout his career, Dr. Gautam Allahbadia has been instrumental in developing new fertility-enhancing protocols and propagating the use of Ultrasound in Embryo Transfer procedures. He is the recipient of over 25 prizes & fellowships, including the Canadian Young Scientist Fellowship Award (1994), the Deutscher Akademischer Austauschdienst Fellowship (1996) for IVF/ICSI training at the University of Gottingen in Germany, and the FOGSI-CORION National Research Award (1998). Dr. Gautam was elected Vice President of the World Association of Reproductive Medicine (WARM) and named “Mumbai’s Top Doc” for 2012 by peer nomination.' ),
	);
	foreach ( $doctors as $doctor ) { brounhall_seed_doctor( $doctor ); }
}
