<?php
defined( 'ABSPATH' ) || exit;

function brounhall_treatment_seed( $slug, $title, $hero, $navigation, $sections, $related = array() ) {
	$post = get_page_by_path( $slug, OBJECT, 'bh_treatment' );
	$id = $post ? $post->ID : wp_insert_post( array( 'post_type' => 'bh_treatment', 'post_status' => 'publish', 'post_title' => $title, 'post_name' => $slug, 'menu_order' => 0 ) );
	if ( is_wp_error( $id ) || ! $id ) { return 0; }
	if ( ! $post ) { update_post_meta( $id, '_brounhall_treatment_data', wp_json_encode( brounhall_normalize_treatment_data( array( 'hero' => $hero, 'navigation' => $navigation, 'sections' => $sections, 'relatedTreatments' => array( 'items' => $related ) ) ), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ) ); }
	return (int) $id;
}

function brounhall_seed_treatments() {
	$disabled = function ( $id, $type = 'rich_text' ) { return array( 'id' => $id, 'type' => $type, 'enabled' => false ); };
	$nav = function ( $key, $label ) { return array( 'key' => $key, 'label' => $label, 'target' => $key ); };
	$b = function ( $title, $href ) { return array( 'key' => sanitize_title( $title ), 'title' => $title, 'description' => '', 'media' => array( 'imageId' => 0, 'alt' => '' ), 'action' => array( 'label' => 'Learn more', 'href' => $href ), 'presentation' => array( 'variant' => 'image' ) ); };
	$common = function ( $title, $highlight, $description, $image_id ) { return array( 'title' => $title, 'titleHighlight' => $highlight, 'description' => $description, 'media' => array( 'imageId' => $image_id, 'alt' => $title ), 'actions' => array() ); };

	brounhall_treatment_seed( 'sperm-freezing', 'Sperm Freezing', $common( 'Sperm Freezing', 'Store sperm for future use', 'Store sperm for future use — including before vasectomy, cancer treatment, or when facing low sperm count.', 1101 ), array( $nav( 'what-is-sperm-freezing', 'What is sperm freezing' ), $nav( 'who-is-sperm-freezing-for', 'Who is sperm freezing for' ) ), array( $disabled( 'what-is-sperm-freezing' ), $disabled( 'who-is-sperm-freezing-for' ) ), array( $b( 'IVF', '/treatments/ivf' ), $b( 'ICSI', '/treatments/icsi' ), $b( 'IUI', '/treatments/iui' ), $b( 'Egg Freezing', '/treatments/egg-freezing' ) ) );
	brounhall_treatment_seed( 'embryo-freezing', 'Embryo Freezing', $common( 'Embryo Freezing', 'Preserve embryos for future transfer', 'Freeze embryos at an early developmental stage for future transfer when the time is right for your family.', 1201 ), array( $nav( 'what-is-embryo-freezing', 'What is embryo freezing' ), $nav( 'when-is-embryo-freezing-used', 'When is embryo freezing used' ) ), array( $disabled( 'what-is-embryo-freezing' ), $disabled( 'when-is-embryo-freezing-used' ) ) );
	brounhall_treatment_seed( 'ivf', 'IVF (In-vitro fertilisation)', $common( 'IVF (In-vitro fertilisation)', "If IVF is part of your fertility journey, you're in expert hands at Bourn Hall", '', 0 ), array( $nav( 'what-is-ivf', 'What is IVF' ), $nav( 'how-does-it-work', 'How does it work' ), $nav( 'stimulation-protocols', 'Stimulation protocols' ), $nav( 'who-is-ivf-for', 'Who is IVF for' ) ), array( $disabled( 'what-is-ivf' ), $disabled( 'how-does-it-work' ), $disabled( 'stimulation-protocols', 'content_groups' ), $disabled( 'who-is-ivf-for', 'eligibility_content' ) ) );
	brounhall_treatment_seed( 'icsi', 'ICSI (Intracytoplasmic Sperm Injection)', $common( 'ICSI (Intracytoplasmic Sperm Injection)', 'Designed to make fertilisation more effective', '', 0 ), array( $nav( 'what-is-icsi', 'What is ICSI' ), $nav( 'how-does-it-work', 'How does it work' ), $nav( 'who-is-icsi-for', 'Who is ICSI for' ) ), array( $disabled( 'what-is-icsi' ), $disabled( 'how-does-it-work' ), $disabled( 'who-is-icsi-for' ) ) );
	brounhall_treatment_seed( 'iui', 'IUI (Intrauterine insemination)', $common( 'IUI (Intrauterine insemination)', 'IUI can improve your chances of becoming pregnant', '', 0 ), array( $nav( 'what-is-iui', 'What is IUI' ), $nav( 'how-does-it-work', 'How does it work' ), $nav( 'who-is-iui-for', 'Who is IUI for' ) ), array( $disabled( 'what-is-iui' ), $disabled( 'how-does-it-work' ), $disabled( 'who-is-iui-for' ) ) );
	brounhall_treatment_seed( 'genetic-testing', 'Genetic testing', $common( 'Genetic testing', 'Pre-implantation Genetic Testing (PGT) of embryos', '', 0 ), array( $nav( 'what-pgt-do-we-offer', 'What type of pre-implantation genetic testing do we offer?' ), $nav( 'pgt-m', 'PGT-M' ), $nav( 'pgt-a', 'PGT-A' ), $nav( 'pgt-sr', 'PGT-SR' ) ), array( array( 'id' => 'what-pgt-do-we-offer', 'type' => 'genetic_testing', 'enabled' => true, 'title' => 'What type of pre-implantation genetic testing does Bourn Hall offer?', 'introduction' => 'Bourn Hall provides pre-implantation genetic testing for:', 'items' => array( array( 'key' => 'pgt-m', 'text' => 'Monogenic diseases (PGT-M)' ), array( 'key' => 'pgt-sr', 'text' => 'Structural chromosomal rearrangements (PGT-SR)' ), array( 'key' => 'pgt-a', 'text' => 'Aneuploidy screening (PGT-A)' ) ), 'closingText' => '' ), $disabled( 'pgt-m' ), $disabled( 'pgt-a' ), $disabled( 'pgt-sr' ) ) );
}
